version: '3.1'
services:
 
  #PHP-APACHE
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-apache
    restart: always
    ports:
      - "8080:80"
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker-volumes/apache_config:/etc/apache2/sites-available
    networks:
      - app-network

  #Mongo
  mongo:
    image: mongo:8.0.0
    container_name: db-mongo
    restart: always
    ports:
      - "27017:27017"
    tty: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
        - ./docker-volumes/mongo_data:/data/db
    networks:
      - app-network

  #Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-network
 
#Network
networks:
  app-network:
    driver: bridge
